# get rider cooridnates
# GET path
# GET http://localhost:3002/rider-coordinates



# post rider coordinates
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
  "lat": 37.7749,
  "lon": -122.4194,
  "riderId": "12345"
}